# Generated by Django 5.0.3 on 2025-04-19 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_operator_address_operator_email_primary_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.tcardcolumn')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_cards', to='events.event')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
            ],
            options={
                'ordering': ['column__position', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TCardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CREATE', 'Card Created'), ('MOVE', 'Moved to Column'), ('UPDATE', 'Card Updated'), ('DELETE', 'Card Deleted')], max_length=10)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('t_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='events.tcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
