# Generated by Django 5.0.3 on 2025-04-18 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 20, 23, 49, 225080, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 20, 23, 55, 729470, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
