# Generated by Django 5.0.3 on 2025-04-18 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_card_columns', to='core.event')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('event', 'position')},
            },
        ),
    ]
