# Generated by Django 5.0.3 on 2025-04-18 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tcardcolumn'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tcardcolumn',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tcardcolumn',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.event'),
        ),
        migrations.AlterField(
            model_name='tcardcolumn',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tcardcolumn',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='tcardcolumn',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tcardcolumn',
            name='updated_at',
        ),
    ]
