# Generated by Django 5.0.3 on 2025-04-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tcardcolumn_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tcardcolumn',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventoperator',
            name='event',
        ),
    ]
