# Generated by Django 5.0.3 on 2025-04-18 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_network_event_remove_tcardcolumn_event_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='events.event'),
        ),
        migrations.RemoveField(
            model_name='eventoperator',
            name='network',
        ),
        migrations.RemoveField(
            model_name='eventoperator',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='operator',
        ),
        migrations.DeleteModel(
            name='TCardColumn',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='EventOperator',
        ),
    ]
