# Generated by Django 5.0.3 on 2025-04-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_activitylog_event_remove_eventoperator_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='email_primary',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='operator',
            name='email_secondary',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='operator',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='operator',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='operatorcredential',
            name='credential',
            field=models.CharField(choices=[('C4', 'C4'), ('F3', 'F3'), ('F2', 'F2'), ('F1', 'F1'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1'), ('P3', 'P3'), ('P2', 'P2'), ('P1', 'P1'), ('S3', 'S3'), ('S2', 'S2'), ('S1', 'S1'), ('E3', 'E3'), ('E2', 'E2'), ('MAC', 'MAC'), ('FIRE', 'FIRE'), ('ERO', 'ERO'), ('UL', 'UL'), ('SHARES', 'SHARES')], max_length=10),
        ),
    ]
