# Generated by Django 5.0.3 on 2025-04-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_operator_address_operator_email_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='name',
        ),
        migrations.AddField(
            model_name='operator',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='operator',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
